#Criando uma Estrutura de Dados para Armazenar a Topologia 
caminhos = list()
caminhos.append({"De" : "S", "Para" : "1", "Dist" : 10})
caminhos.append({"De" : "S", "Para" : "2", "Dist" : 10})
caminhos.append({"De" : "1", "Para" : "3", "Dist" : 4})
caminhos.append({"De" : "1", "Para" : "2", "Dist" : 2})
caminhos.append({"De" : "1", "Para" : "4", "Dist" : 8})
caminhos.append({"De" : "2", "Para" : "4", "Dist" : 9})
caminhos.append({"De" : "3", "Para" : "T", "Dist" : 10})
caminhos.append({"De" : "4", "Para" : "3", "Dist" : 6})
caminhos.append({"De" : "4", "Para" : "T", "Dist" : 10})

cidades = list()
cidades.append({"No" : "S", "Custo" : "Dummy", "Dec_Otima" : "Dummy"})
cidades.append({"No" : "1", "Custo" : "Dummy", "Dec_Otima" : "Dummy"})
cidades.append({"No" : "2", "Custo" : "Dummy", "Dec_Otima" : "Dummy"})
cidades.append({"No" : "3", "Custo" : "Dummy", "Dec_Otima" : "Dummy"})
cidades.append({"No" : "4", "Custo" : "Dummy", "Dec_Otima" : "Dummy"})
cidades.append({"No" : "T", "Custo" : "Dummy", "Dec_Otima" : "Dummy"})
